init: crud diario
sisgha/sisgha-backend pull request #32
Opened 2024-03-16 18:59 UTC by GabrielOlisil

2024-03-16 19:04 UTC, GabrielOlisil commented
[Não sei solicitar pr](https://www.youtube.com/watch?v=E3RcD6LleYU&ab_channel=GreenScreenClips)

2024-03-16 19:36 UTC, guesant requested changes

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/dtos/diario.dto.ts
> +  ambientePadrao!: AmbienteEntity | null;
IAmbienteModel

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/dtos/diario.dto.ts
> +  disciplina!: DisciplinaEntity;
IDisciplinaModel

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/dtos/diario.dto.ts
> +    situacao: yup.mixed(), // diario
ValidationContractString().required().defined()

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/dtos/diario.dto.ts
> +    etapa: yup.mixed(), // diario
ValidationContractString().required().defined()

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/dtos/diario-update.operation.ts
> +  disciplina?: DisciplinaEntity;
IObjectUuid

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/dtos/diario-update.operation.ts
> +  ambientePadrao?: AmbienteEntity | null;
IObjectUuid

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/dtos/diario-find-one.operation.ts
> +  disciplina!: DisciplinaEntity;
IDisciplinaModel

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/dtos/diario-find-one.operation.ts
> +  ambientePadrao!: AmbienteEntity | null;
IAmbienteModel

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/dtos/diario-find-all.operation.ts
> +      //
filter.

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/(spec)/ensino/diario/operations/diario-input/IDiarioUpdateDto.ts
> +  disciplina?: IDisciplinaModel;
IObjectUuid

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/(spec)/ensino/diario/operations/diario-input/IDiarioUpdateDto.ts
> +  ambientePadrao?: IAmbienteModel | null;
IObjectUuid

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/(spec)/ensino/diario/operations/diario-input/IDiarioUpdateDto.ts
> +  turma?: ITurmaModel;
IObjectUuid

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/dtos/diario.dto.ts
> +  turma!: TurmaEntity;
ITurmaModel

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/(spec)/ensino/diario/operations/diario-find-one/IDiarioFindOneResultDto.ts
> +export interface IDiarioFindOneResultDto extends Pick<IDiarioModel, 'id' | 'situacao' | 'ano' | 'etapa' | 'turma' | 'disciplina' | 'ambientePadrao'> {}
tirar `| 'turma' | 'disciplina' | 'ambientePadrao'`

colocar dentro do `{}`


```js
{
  turma: ITurmaFindOneResultDto,
  disciplina: IDisciplinaFindOneResultDto,
  ambientePadrao: IAmbienteFindOneResultDto | null,
}
```

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/diario.service.ts
> +    qb.addSelect([`${alias}.id`, `${alias}.situacao`, `${alias}.ano`, `${alias}.etapa`, `${alias}.turma`, `${alias}.disciplina`, `${alias}.ambientePadrao`]);
remover 

```
`${alias}.turma`, `${alias}.disciplina`, `${alias}.ambientePadrao`
```

trocar alias para aliasDiario

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/diario.service.ts
> +      filterableColumns: {},
'turma.id': [FilterOperator.EQ],
'disciplina.id': [FilterOperator.EQ],
'ambientePadrao.id': [FilterOperator.EQ],

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/diario.service.ts
> +        'turma',
trocar para turma.id

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/diario.service.ts
> +        'disciplina',
trocar para disciplina.id

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/diario.service.ts
> +        'ambientePadrao',
trocar para ambientePadrao.id

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/diario.service.ts
> +        'turma',
trocar por turma.nome

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/diario.service.ts
> +        'disciplina',
trocar por disciplina.nome

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/diario.service.ts
> +        'ambientePadrao',
ambientePadrao.nome

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/diario.service.ts
> +        'turma',
'turma.periodo',
'turma.grupo',
'turma.nome',

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/diario.service.ts
> +        'disciplina',
disciplina.nome

2024-03-16 19:36 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/diario.service.ts
> +        'ambientePadrao',
tirar 'ambientePadrao'

2024-03-16 19:40 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/dtos/diario.dto.ts
> +    ano: yup.mixed(), // diario
ValidationContractNumber().integer().positive().required()

2024-03-16 19:42 UTC, guesant commented
> [Não sei solicitar pr](https://www.youtube.com/watch?v=E3RcD6LleYU&ab_channel=GreenScreenClips)

@escuderoDP

2024-03-18 03:22 UTC, GabrielOlisil commented on luna-backend/src/application/business/ensino/diario/dtos/diario-find-all.operation.ts
> +      //
Dessa forma maninho???

```js
swagger: {
    returnType: DiarioFindAllResultDto,

    queries: [
      //
      'page',
      'limit',
      'search',
      'sortBy',
      'filter'
      //
    ],
  },

```

2024-03-18 03:29 UTC, GabrielOlisil commented on luna-backend/src/application/business/ensino/diario/diario.service.ts
> +    qb.addSelect([`${alias}.id`, `${alias}.situacao`, `${alias}.ano`, `${alias}.etapa`, `${alias}.turma`, `${alias}.disciplina`, `${alias}.ambientePadrao`]);
olhando melhor acho que não precisa mudar o alisa pra aliasDiario nao pq o alias enviado pra função ja é o alias diario

`line 92`
```ts
DiarioService.DiarioQueryBuilderView(aliasDiario, qb, {});
```

2024-03-18 09:52 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/dtos/diario-find-all.operation.ts
> +      //
'filter.turma.id',
'filter.disciplina.id',
'filter.ambientePadrao.id'

2024-03-18 09:55 UTC, guesant commented on luna-backend/src/application/business/ensino/diario/diario.service.ts
> +    qb.addSelect([`${alias}.id`, `${alias}.situacao`, `${alias}.ano`, `${alias}.etapa`, `${alias}.turma`, `${alias}.disciplina`, `${alias}.ambientePadrao`]);
Ótima observação

2024-03-18 12:57 UTC, merged