Ssgdha 100 crud de calend rio letivo
sisgha/sisgha-backend pull request #34
Opened 2024-03-18 21:15 UTC by PeHMB

2024-03-19 00:24 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo.dto.ts
> +@ObjectType('Calendario-letivo')
CalendarioLetivo

2024-03-19 00:24 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/calendario-letivo.controller.ts
Faltaram as outras rodas (findOne, create, update e delete).

2024-03-19 00:26 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/calendario-letivo.module.ts
Aqui, será necessário iniciar a array `imports`. Isso é, para o nosso create e update validar corretamente se campus e modalidade existem, precisamos usar o campusService e modalidadeService dentro de CalendarioLetivoService. Para isso, será necessário adicionar:

```ts
@Module({
    imports :[
        CampusModule,
        ModalidadeModule,
    ],
})
```

2024-03-19 00:26 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/calendario-letivo.resolver.ts
Faltou a outra query (findOne) e as outras mutations (create, update e delete).

2024-03-19 00:27 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-find-one.operation.ts
> +  campus!: CampusEntity;
Aqui poderia ser ICampusModel

2024-03-19 00:27 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-find-one.operation.ts
> +  modalidade!: ModalidadeEntity;
Aqui poderia ser IModalidadeModel

2024-03-19 00:29 UTC, guesant commented on luna-backend/src/main.ts
> +  config.addTag('Calendarios');
Seguir a ordem de precedência feita na Documentação de Entidades.

Além disso, adicionar um seguindo parâmetro à função addTag: 

```ts
config.addTag('Calendarios Letivos', 'Calendario / Calendarios Letivos');
```

Visto que será alterada o nome da tag de `Calendarios` para `Calendarios Letivos` - e lembre de não usar acentos -, será necessários atualizar no calendario-letivo.controller:

De:

```ts
@ApiTags('Calendarios')
```

Para

```ts
@ApiTags('Calendarios Letivos')
```

2024-03-19 00:30 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo.dto.ts
> +    campus!: CampusEntity;
Aqui poderia ser ICampusModel

2024-03-19 00:30 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo.dto.ts
> +    modalidade!: ModalidadeEntity;
Aqui poderia ser IModalidadeModel

2024-03-19 00:31 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo.dto.ts
> +            type: () => CursoDto,
Aqui refere-se a Campus, mas está usando a classe de curso: `CursoDto`.

2024-03-19 00:31 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo.dto.ts
> +            type: CursoFindOneResultDto,
Aqui refere-se a Campus, mas está usando a classe de curso: `CursoFindOneResultDto`.

2024-03-19 00:32 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo.dto.ts
> +        campus: ValidationContractObjectUuid({ required: true }).defined().required(),
Agora (na branch development, acredito que sua branch ainda não tenha essa função), será utilizado outra função para validar os relacionamentos de entrada:

```ts
  campus: ValidationContractObjectUuidBase({ required: false, optional: false }),
```

2024-03-19 00:32 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo.dto.ts
> +        modalidade: ValidationContractObjectUuid({ required: true }).defined().required(),
Agora (na branch development, acredito que sua branch ainda não tenha essa função), será utilizado outra função para validar os relacionamentos de entrada:

```ts
  modalidade: ValidationContractObjectUuidBase({ required: false, optional: false }),
```

2024-03-19 00:35 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-update.operation.ts
> +export const CalendarioLetivoUpdateInputDtoValidationContract = createValidationContract(() => {
Estrutura de um UpdateInputDtoValidationContract refatorado: 

```ts
export const TurmaUpdateInputDtoValidationContract = createValidationContract(() => {
  const schema = TurmaInputDtoValidationContract();

  return (
    yup
      //
      .object()
      .concat(TurmaFindOneByIdInputValidationContract())
      .concat(schema.pick(['nome', 'periodo', 'grupo']).partial())
      .shape({
        curso: ValidationContractObjectUuidBase({ required: true, optional: true }),
        ambientePadraoAula: ValidationContractObjectUuidBase({ required: false, optional: true }),
      })
  );
});
```


Note que agora é feito o pick() dos atributos simples, e agora é usada a função `ValidationContractObjectUuidBase` em vez de `getSchemaSubpath`.

Essa nova função aceita outra configuração chamada de `optional`. No caso, é opcional passar essa informação nos updates. Então, esse validation contract refatorado ficaria assim:

```ts
export const CalendarioLetivoUpdateInputDtoValidationContract = createValidationContract(() => {
  const schema = CalendarioLetivoInputDtoValidationContract();

  return (
    yup
      //
      .object()
      .concat(CalendarioLetivoFindOneByIdInputValidationContract())
      .concat(schema.pick(['nome', 'ano']))
      .shape({
        campus: ValidationContractObjectUuidBase({ required: true, optional: true }),
        modalidade: ValidationContractObjectUuidBase({ required: true, optional: true }),
      })
  );
});
```

2024-03-19 00:36 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-update.operation.ts
> +  campus!: CampusEntity;
ICampusModel

2024-03-19 00:36 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-update.operation.ts
> +  modalidade!: ModalidadeEntity;
IModalidadeModel

2024-03-19 00:36 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-input.operation.ts
> +  campus!: CampusEntity;
IObjectUuid

2024-03-19 00:45 UTC, guesant requested changes

2024-03-19 00:45 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-input.operation.ts
> +  modalidade!: ModalidadeEntity;
IObjectUuid

2024-03-19 00:45 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-input.operation.ts
> +  @DtoProperty(CalendarioLetivoDtoProperties.CALENDARIO_LETIVO_CAMPUS_OUTPUT)
Usar o `_INPUT` em vez de `_OUTPUT`: `CALENDARIO_LETIVO_CAMPUS_INPUT`.

2024-03-19 00:45 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-input.operation.ts
> +  @DtoProperty(CalendarioLetivoDtoProperties.CALENDARIO_LETIVO_MODALIDADE_OUTPUT)
Usar o `_INPUT` em vez de `_OUTPUT`: `CALENDARIO_LETIVO_MODALIDADE_INPUT`.

2024-03-19 00:45 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-input.operation.ts
> +    campus: getSchemaField(schema, 'campus'),
remover a linha devido a nova estrutura do código `campus: getSchemaField(schema, 'campus'),`

2024-03-19 00:45 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-input.operation.ts
> +    modalidade: getSchemaField(schema, 'modalidade'),
remover a linha devido a nova estrutura do código `modalidade: getSchemaField(schema, 'modalidade'),`

2024-03-19 00:45 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-delete-one.operation.ts
> +  description: 'Realiza a remoção de "CalendarioLetivo" por ID.',
em todos os dtos, "CalendarioLetivo" poderia ficar mais natural, tipo:

Realiza a remoção de um calendário letivo por ID.

2024-03-19 00:45 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-create.operation.ts
> +
Realmente qnd vc fez, n tinha o validation contract para o create. Mas agora, acredito que seja uma boa termos. É praticamente a mesma coisa da nova versão de update, com a diferença de `optional` sendo `false`.

```ts
export const CalendarioLetivoCreateInputDtoValidationContract = createValidationContract(() => {
  const schema = CalendarioLetivoInputDtoValidationContract();

  return (
    yup
      //
      .object()
      .concat(CalendarioLetivoFindOneByIdInputValidationContract())
      .concat(schema.pick(['nome', 'ano']))
      .shape({
        campus: ValidationContractObjectUuidBase({ required: true, optional: false }),
        modalidade: ValidationContractObjectUuidBase({ required: true, optional: false }),
      })
  );
});
```

2024-03-19 00:45 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-create.operation.ts
> +        inputDtoValidationContract: CalendarioLetivoDtoValidationContract,
Usar `CalendarioLetivoCreateInputDtoValidationContract`.

2024-03-19 00:45 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-create.operation.ts
> +        inputBodyValidationContract: CalendarioLetivoDtoValidationContract,
Usar `CalendarioLetivoCreateInputDtoValidationContract`.

2024-03-19 00:45 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/calendario-letivo.service.ts
> +const aliasCalendarioLetivo = 'calendario-letivo';
Nos queryBuilders, vamos seguir a padronização calendarioLetivo

2024-03-19 00:45 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/calendario-letivo.service.ts
> +    const dtoCalendarioLetivo = pick(dto, ['nome', 'ano', 'campus', 'modalidade']);
Pode remover o `, 'campus', 'modalidade'`, visto que serão colocados abaixo.

```ts
const dtoCalendarioLetivo = pick(dto, ['nome', 'ano']);
```

2024-03-19 00:45 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/calendario-letivo.service.ts
> +  async CalendarioLetivoFindByIdSimple(
começar com c minúsculo

2024-03-19 00:45 UTC, guesant commented on luna-backend/src/application/business/calendario/calendario-letivo/calendario-letivo.service.ts
> +        'campus',
cara... eu n sei, mas acho que todas os atributos que são usados no `sortableColumns`, `searchableColumns` e `filterableColumns` devem estar no `select`.

2024-03-24 01:28 UTC, PeHMB commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-input.operation.ts
> +  campus!: CampusEntity;
Não entendi onde essa alteração deve ser feita

2024-03-24 01:28 UTC, PeHMB commented on luna-backend/src/application/business/calendario/calendario-letivo/dtos/calendario-letivo-input.operation.ts
> +  modalidade!: ModalidadeEntity;
Não entendi onde essa alteração deve ser feita

2024-03-24 01:29 UTC, PeHMB commented on luna-backend/src/application/business/calendario/calendario-letivo/calendario-letivo.service.ts
> +        'campus',
Não entendi onde essa alteração deve ser feita

2024-03-24 11:52 UTC, guesant approved these changes

2024-03-24 11:54 UTC, merged